version: '3.7'
services:
  gitlab-web:
    image: 'gitlab/gitlab-ee:16.1.2-ee.0'
    restart: always
    hostname: 'gitlab-web-host'
    container_name: gitlab-ee
    environment:
      GITLAB_OMNIBUS_CONFIG: |
        external_url 'http://localhost'
    ports:
      - '12901:80'
      - '12902:443'
      - '12903:22'
    volumes:
      - './persistence/config:/etc/gitlab'
      - './persistence/logs:/var/log/gitlab'
      - './persistence/data:/var/opt/gitlab'
    networks:
      - gitlab-network
  gitlab-runner:
    image: gitlab/gitlab-runner:alpine3.18-v16.1.0
    container_name: gitlab-runner    
    restart: always
    depends_on:
      - gitlab-web
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - './persistence/gitlab-runner:/etc/gitlab-runner'
    networks:
      - gitlab-network

networks:
  gitlab-network:
    driver: bridge
